language: scala
scala:
  - 2.9.1
  
  
jdk:
    
    - openjdk7

services:
  - mongodb
  - memcache

env:
  - PLAY_VERSION=2.0

before_script:
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip
 
notifications: 
  email: false
